[package]
name = "shamirsecretsharing-rs"
version = "0.0.1"
authors = ["arnaucube <arnaucube@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
num = "0.2.0"
num-bigint = {version = "0.2.2", features = ["rand"]}
num-traits = "0.2.8"
